# prod.yml

version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: youtube_app
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             gunicorn -c gunicorn_config.py"
    volumes:
      - ./youtube_data_fetch:/youtube_data_fetch
      - ./youtube_data_fetch/media:/youtube_data_fetch/media
    env_file:
      - .env
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    container_name: nginx_server
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./youtube_data_fetch/media:/youtube_data_fetch/media
      - ./youtube_data_fetch/static:/youtube_data_fetch/static
    ports:
      - "80:80"
    depends_on:
      - web
