# prod.yml

version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: youtube_app
    command: gunicorn youtube_data_fetch.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./youtube_data_fetch:/app
      - ./youtube_data_fetch/media:/app/media
    env_file:
      - .env
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    container_name: nginx_server
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./youtube_data_fetch/media:/app/media
      - ./youtube_data_fetch/static:/app/static
    ports:
      - "80:80"
    depends_on:
      - web
