# Generated by Django 5.1.2 on 2024-10-15 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, unique=True)),
                ('video_file', models.FileField(upload_to='videos_data')),
                ('comment_file', models.FileField(upload_to='comments_data')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('published_at', models.DateTimeField()),
                ('duration', models.CharField(max_length=20)),
                ('view_count', models.PositiveBigIntegerField(blank=True, null=True)),
                ('like_count', models.PositiveBigIntegerField(blank=True, null=True)),
                ('comment_count', models.PositiveBigIntegerField(blank=True, null=True)),
                ('default_thumbnail', models.URLField(blank=True, null=True)),
                ('medium_thumbnail', models.URLField(blank=True, null=True)),
                ('high_thumbnail', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=20)),
                ('comment_id', models.CharField(max_length=50, unique=True)),
                ('comment_text', models.TextField()),
                ('author_name', models.CharField(max_length=100)),
                ('published_at', models.DateTimeField()),
                ('like_count', models.PositiveIntegerField(blank=True, null=True)),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='youtube.comment')),
            ],
        ),
    ]
